version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.1.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
#          fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn test
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
      docker:
        - image: google/cloud-sdk

      working_directory: ~/repo

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
  #          fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run: yarn deploy

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  dev:
    jobs:
      - build_and_test
  prod:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

