version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.1.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
#          fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn test
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: deploy/
          destination: deploy

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

#      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
#      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: ./deploy/deploy_ci.sh

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

