version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.1.2

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
#          fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn test
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: deploy/MovieMarathon
          destination: build

      - persist_to_workspace:
          root: .
          paths:
            - deploy/*


  deploy:
    docker:
      - image: google/cloud-sdk

    steps:
      - attach_workspace:
          at: .
      - run: ./deploy/deploy_ci.sh

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

