version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
#          fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn test
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: dist-dev
          destination: build

      - persist_to_workspace:
          root: .
          paths:
            - dist-dev

